### ISSUE TITLE
Unable to install on 1.49.1

### ISSUE THREAD

**Issue by jrgparamo** [Llewellyn500/Legendary-Dark#1]
I tried installing the theme via marketplace and got this message.

![Screenshot_2020-10-28_15-55-11](https://user-images.githubusercontent.com/3992139/97495901-36029780-1936-11eb-8f84-8a0ff8f23b6f.png)
)

**Comment by Llewellyn500** [comment]
Please can't you update your VsCode? but anyway I've changed the compatible version so you should be able to download it now.
